# Generated by Django 3.2.15 on 2022-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game_medium',
            field=models.CharField(choices=[('video_games', 'Video games'), ('boardgames', 'Boardgames'), ('card_games', 'Card games'), ('game_art', 'Game art'), ('other', 'Other')], default='games', max_length=15),
        ),
    ]
