# Generated by Django 3.2.15 on 2022-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('real_time', 'Real-time strategy'), ('shooters', 'Shooters (FPS and TPS)'), ('mmo', 'MMO'), ('role_playing', 'Role-playing'), ('simulation_and_sport', 'Simulation and sports'), ('puzzle_party', 'Puzzler and party'), ('action_adventure', 'Action and adventure'), ('survival_horror', 'Survival and horror'), ('platformer', 'Platformer')], default='other', max_length=50),
        ),
    ]
